version: '3.8'

name: cfa

services:
  composer:
    container_name: composer-gui
    build:
      context: .
      target: builder
      dockerfile: ./infrastructure/Dockerfile
    volumes:
      - .:/var/www
    entrypoint: "composer install --no-interaction --no-ansi --no-scripts --classmap-authoritative"
    networks:
        - proxy

  gui:
    container_name: gui
    build:
      context: .
      target: prod
      dockerfile: ./infrastructure/Dockerfile
    image: gui:latest
    ports:
      - "8002:80"
    depends_on:
      - composer
    volumes:
      - .:/var/www
    working_dir: /var/www
    entrypoint: "/etc/entrypoint.sh"
    healthcheck:
          test: curl --fail http://gui:8002/ || exit 1
          interval: 40s
          timeout: 30s
          retries: 3
          start_period: 60s
    networks:
        - proxy

networks:
    proxy:
        name: proxy
        external: true
