openapi: 3.0.0
info:
  title: CRUD de Usuário API
  description: API para operações CRUD em usuários
  version: 1.0.0
servers:
  - description: Localhost
    url: http://127.0.0.1:8000/api/
paths:
  /usuarios:
    get:
      summary: Lista todos os usuários
      responses:
        '200':
          description: Lista de usuários recuperada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '400':
          description: Erro ao buscar usuário
    post:
      summary: Cria um novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Falha ao adicionar usuário
  /usuarios/{id}:
    get:
      summary: Obtém um usuário pelo ID
      parameters:
        - in: path
          name: id
          required: true
          description: ID do usuário a ser obtido
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Usuário recuperado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Usuário não encontrado

    put:
      summary: Atualiza um usuário existente pelo ID
      parameters:
        - in: path
          name: id
          required: true
          description: ID do usuário a ser atualizado
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Usuário atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Usuário não encontrado
        '400':
          description: Falha ao atualizar usuário

    delete:
      summary: Remove um usuário pelo ID
      parameters:
        - in: path
          name: id
          required: true
          description: ID do usuário a ser removido
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Usuário removido com sucesso
        '404':
          description: Usuário não encontrado
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID do usuário
        name:
          type: string
          description: Nome do usuário
        email:
          type: string
          format: email
          description: Email do usuário
        password:
          type: integer
          description: Senha do usuário
        photo:
          type: integer
          description: Caminho para foto do usuário
        interfaceLanguage:
          type: integer
          description: Idioma da interface do usuário
        group:
          type: integer
          description: grupo do usuário
      required:
        - name
        - email
